validate_response:
  description: >
    Validate the user's response to ensure there are clear, executable tasks present. 
    If there are no tasks requested, ask the user to clarify.
    If there are tasks requested, but they aren't sufficiently clear to be executed, ask for clarification specific to those statements.
  expected_output: >
    - A boolean indicating whether clarification is needed.
  agent: manager

split_tasks:
  description: >
    Split the user's input into a list of tasks that can be completed independently by separate engineers.
    Each task should be clear and executable, with no ambiguity.
  expected_output: >
    - A list of tasks.
  agent: manager

read_system:
  description: >
    Read the user's current file system and identify the files relevant to {task} that need to be modified, returning their contents.
  expected_output: >
    - A schema of the file structure, with paths.
    - The contents of the files that should be modified for {task}.
  agent: file_reader

make_changes:
  description: >

  expected_output: >
  context:
    - read_system
  agent: engineer

create_branch:
  description: >
    Create a new branch in git for {task} and switch to it.
  expected_output: >
    - Confirmation of the new branch creation and switch or error.
  agent: engineer

commit_changes:
  description: >
    Commit changes onto the current branch.
  expected_output: >
    - Confirmation of the changes being committed or error.
  agent: engineer

merge_pr:
  description: >
    
  expected_output: >
    
  agent: git_manager
  context: >

  output_file: 
