validate_response:
  description: >
    Validate the user's response to ensure there are clear, executable tasks present. 
    If there are no tasks requested, ask the user to clarify.
    Read the user's current file system and file contents to contextualize the user's request.
    Identify if there's anything the user is referring to that is needed to understand the request that cannot be found in the system that may need clarification.
    If there are tasks requested, but they aren't sufficiently clear to be executed, ask for clarification specific to those statements.
  expected_output: >
    - A boolean indicating whether clarification is needed.
  agent: manager

split_tasks:
  description: >
    Split the user's input into a list of tasks that can be completed independently by separate engineers.
    Each task should be clear and executable, with no ambiguity.
  expected_output: >
    - A list of tasks as strings.
  output_pydantic: true
  agent: manager