make_changes:
  name: "Make changes"
  description: >
    Think about steps required to complete {task}.
    Edit user files to complete {task}.
  expected_output: >
    - Summary of changes made to files.
  agent: engineer