read_system:
  description: >
    Read the user's current file system and identify the files relevant to {task} that need to be modified, returning their contents.
  expected_output: >
    - A schema of the file structure, with paths.
    - The contents of the files that should be modified for {task}.
  agent: engineer

make_changes:
  description: >
    Think about steps required to complete {task}.
    Edit user files to complete {task}.
  expected_output: >
    - Summary of changes made to files.
  context:
    - read_system
  agent: engineer

create_branch:
  description: >
    Create a new worktree (branch) in git for {task} and switch to it.
  expected_output: >
    - Confirmation of the new worktree creation and switch or error.
  agent: engineer

commit_changes:
  description: >
    Commit changes onto the current worktree.
  expected_output: >
    - A summary of the changes made in the commit.
  agent: engineer
